name: .NET Code Coverage

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: '.NET SDK version to use'
        required: false
        type: string
        default: '8.x'
      build-configuration:
        description: 'Build configuration'
        required: false
        type: string
        default: 'Release'
    secrets:
      # CHECKOUT_TOKEN is defined for when jobs are added to this workflow
      CHECKOUT_TOKEN:
        description: 'Token for private repository checkout'
        required: false
        
